baseURL = 'https://atlasadmin.cl/'
languageCode = 'es-cl'
defaultContentLanguage = 'es'
title = 'Atlas Administración'
disableKinds = ['taxonomy', 'term']

[params]
description = "Atlas Administración - Servicios de administración y gestión de propiedades en Chile"
email = "hola@atlasadmin.cl"
phone = "+56 9 4254 3621"
address = "Santiago, Chile"
linkedin = "https://www.linkedin.com/company/atlasadmin"
copyright = "Atlas Administración © 2024. Todos los derechos reservados."
    images = ['/images/og-image.jpg']
    mainSections = ['services', 'about']

[markup.goldmark.renderer]
    unsafe = true

[build]
    command = "git submodule update --init --recursive"

[minify]
    disableHTML = false
    minifyOutput = true

[security.funcs]
    getenv = ['^HUGO_', '^GA_']

[menu]
    [[menu.main]]
        name = "Inicio"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Servicios" 
url = "/servicios/"
        weight = 2
    [[menu.main]]
name = "Nosotros"
url = "/nosotros/"
        weight = 3
    [[menu.main]]
name = "Contacto"
url = "/contacto/"
weight = 4
