baseURL = 'https://nicolaslandaeta.github.io/atlasadmin/'
languageCode = 'es'
title = 'Atlas Administración'

disableKinds = ['taxonomy', 'term']

[params]
    description = "Oficina de Administración"

[menu]
    [[menu.main]]
        name = "Inicio"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Servicios"
        url = "/services"
        weight = 2
    [[menu.main]]
        name = "Sobre Nosotros"
        url = "/about"
        weight = 3